<!--TO DO: Keine Ahnung wo das hier hin soll und was das ist. Autor:unbekannt -->
<div name="biofakt">

     
    <p><h1><b>Biologische Parameter</b></h1></p>
    <p><b>&auml;u&szlig;ere Merkmale des Wassers - Wassertiefe, Sichttiefe, Geruch</b></p>
    <p>Die Schilfpflanze bildet einen geschlossenen Rohrwald bis 1,2-2 m Tiefe. Au&szlig;erdem ist Schilf an die Land-Wasser-&Uuml;bergangszone angepasst. Eine deutliche Tr&uuml;bung des Wassers kann durch Algen, organische Belastung und auch mineralische Bestandteile hervorgerufen werden. Verunreinigungen mit Abwasser lassen eine meist graue F&auml;rbung entstehen. Zudem l&auml;sst sich am Geruch die G&uuml;te des Gew&auml;ssers erkennen, da ein muffiger Geruch auf eine Sauerstoffarmut schlie&szlig;en l&auml;sst. Eine Schaumbildung deutet auf eine organische Belastung hin, wobei die Ursache zivilisatorisch oder biologisch sein kann. Eine Tr&uuml;bung des Wassers kann au&szlig;erdem den Nebeneffekt haben, dass sich das Gew&auml;sser aufheizt und somit zus&auml;tzlich die Sauerstoffkonzentration sinkt, da bei zunehmender Temperatur die L&ouml;slichkeit von Sauerstoff in Wasser sinkt. </p>
    <p><b>Wassertemperatur und Flie&szlig;geschwindigkeit</b></p>
    <p>Wie bereits erw&auml;hnt, kann die Wassertemperatur bei mittlerer Sauerstoffkonzentration zum limitierenden Faktor f&uuml;r die Lebensf&auml;higkeit der Organismen wirken, da bei h&ouml;herer Temperatur weniger Sauerstoff im Wasser gel&ouml;st werden kann. Sollte die Wassertemperatur ohne merkliche Wetterunterschiede steigen, so kann dies ein Indikator f&uuml;r zivilisatorische Einfl&uuml;sse wie zum Beispiel Kraftwerk- und Fabrikleitungen sein.  Mit sinkender Konzentration sinkt bei gleicher Ammoniumkonzentration und gleichem pH-Wert die Konzentration des fischtoxischen Ammoniaks bis auf ein Viertel, w&auml;hrend die Fischtoxit&auml;t von gel&ouml;stem Kohlenstoffdioxid steigt.</p>
    <p>Schilfbest&auml;nde an den Uferzonen verringern die Flie&szlig;geschwindigkeit des Gew&auml;ssers und tragen dazu bei, dass ein Verlandungsprozess eintritt, welcher neue  Lebensr&auml;ume durch Schlickablagerungen entstehen l&auml;sst. Bei einer zu hohen Flie&szlig;geschwindigkeit k&ouml;nnen keine Schilfpflanzen mehr wachsen. Zus&auml;tzlich tr&auml;gt eine geringe Flie&szlig;geschwindigkeit dazu bei, dass Algen mehr Zeit haben sich zu vermehren, was die organische Belastung des Gew&auml;ssers f&ouml;rdert.</p>
    <p><b>Bruchfestigkeit</b></p>
    <p>Die Frage der Bruchfestigkeit gilt unter den Experten als ein umstrittener Gegenstand im Hinblick auf das Schilfsterben, da die Abnahme der Bruchfestigkeit oft der Eutrophierung der Seen und Gew&auml;sser angelastet wird, auf der anderen Seite jedoch behauptet wird, dass der eigentliche Schadensfaktor eine zunehmende mechanische Belastung ist, zum Beispiel durch Wind und Treibholz. </p>
    <p>Des Weiteren wird das Schilfsterben der Vermehrungstechnik der Schilfpflanze angelastet, da jene sich haupts&auml;chlich vegetativ und nicht geschlechtlich vermehrt. </p>
        
</div>