<!--Keine Ahnung, was das ist und wo das hin soll. Autor:unbekannt -->
<div name="abiofakt">

    
    <p><b><h1>Chemische Parameter</b></p></h1>
    <p><b>Sauerstoffgehalt und BSB5-Wert</b></p>
    <p>Da jedes Lebewesen Sauerstoff verbraucht, ist der Sauerstoffgehalt eines Gew&auml;ssers ma&szlig;gebend f&uuml;r die Lebensgemeinschaften der tierischen und pflanzlichen Organismen. Im Idealfall wird der verbrauchte Saurestoff durch den Austausch mit der Luft und durch die schrittweise Stoffumwandlung k&ouml;rperfremder in k&ouml;rpereigene Stoffe wieder ersetzt, so dass die Sauerstoffs&auml;ttigung bei 100% liegen sollte. Falls das Gew&auml;sser einer hohen organischen Belastung ausgesetzt ist, f&uuml;hrt dies zu einer hohen Sauerstoffzehrung, da Bakterien das organische Material zu anorganischem Material umbauen und das Gew&auml;sser mineralisieren. Eine Sauerstoff&uuml;bers&auml;ttigung tritt bei einer &uuml;berh&ouml;hten Biomasse an Algen aufgrund eines &uuml;berangebots von Nahrung auf. Eine Sauerstoff&uuml;bers&auml;ttigung ist deshalb gef&auml;hrlich, weil durch die schnelle Ver&auml;nderung des Gasdruckes im Wasser die Gasblasenkrankheit bei Fischen auftreten kann. </p>
    <p>Der BSB5-Wert ist ein Summenparameter, welcher den biochemischen Sauerstoffbedarf in f&uuml;nf Tagen reflektiert. Innerhalb von f&uuml;nf Tagen werden etwa 70% der biologisch abbaubaren Stoffe durch Bakterien im Wasser abgebaut. Demzufolge ist ein hoher BSB5-Wert ein Indikator f&uuml;r ein &uuml;berma&szlig; an leicht abbaubaren organischen Substanzen wie Algen. Ein niedriger BSB5-Wert legt eine geringe Belastung des Gew&auml;ssers nahe, jedoch kann ein niedriger Wert auch ein Indiz f&uuml;r eine chemische Belastung des Gew&auml;ssers sein, welche die Lebensf&auml;higkeit der Organismen einschr&auml;nkt. Ein mittlerer BSB5-Wert zeigt im positiven Sinn also die biologische Aktivit&auml;t des Gew&auml;ssers an. </p>
    <p><b>pH-Wert </b></p>
    <p>Die Skala des pH-Wertes von 0 bis 14 zeigt die Konzentration von Hydroxoniumionen (H3O<sup>+</sup>) und Hydroxidionen (OH<sup>-</sup>) an, welche den sauren oder basischen Charakter des Wassers bestimmen. Wie bei den meisten abiotischen Faktoren besitzen die Organismen verschiedene Pr&auml;ferenz- und Toleranzbereiche, so dass auch der pH-Wert das Tier- und Pflanzenvorkommen bestimmt. Der pH-Wert unterliegt einem tageszeitlichen sowie jahreszeitlichen Rhythmus. Pflanzliche Biomasseproduktion f&uuml;hrt zu einem Anstieg des pH-Wertes, welcher normalerweise zwischen 7,5 und 8,5 liegen sollte. Bei sinkendem pH-Wert wirken Nitritionen und Phenole st&auml;rker giftig, w&auml;hrend Ammoniak als ungiftiges Ammonium gebunden wird. </p>
    <p><b>Leitf&auml;higkeit und Wasserh&auml;rte</b></p>
    <p>Eine Messung der elektrischen Leitf&auml;higkeit erlaubt eine pauschale Beurteilung der Gesamtionen- oder Salzkonzentration, da die Leitf&auml;higkeit zunimmt, wenn Ionen vorhanden sind, welche die Ladungen transportieren. Im Wasser herrscht jedoch auch eine gewisse Konzentration von H3O<sup>+</sup>- und OH<sup>-</sup>-Ionen vor, welche sehr beweglich sind und somit eine pH-Wert- Messung notwendig machen um die Ergebnisse in Verh&auml;ltnis zu setzen. Eine erh&ouml;hte Leitf&auml;higkeit gibt Anlass zur Vermutung eines &uuml;berh&ouml;hten Gebrauchs an D&uuml;ngemitteln, Winterstreuung, geologische Ver&auml;nderungen und Abfall.</p>
    <p>Die Wasserh&auml;rte gibt auf der anderen Seite den Gesamtanteil der gel&ouml;sten Calcium- und Magnesiumverbindungen sowie Spuren von Barium und Strontium an. Diese Verbindungen l&ouml;sen sich im Wasser, wenn es durch Gesteinsschichten sickert, was die regionalen Unterschiede der Wasserh&auml;rte erkl&auml;rt. Heutzutage wird die Wasserh&auml;rte in drei Kategorien eingeteilt, wobei eine Wasserh&auml;rte von 0&deg; dH- 8,4&deg; dH als weich bezeichnet wird und die Spannen f&uuml;r mittleres Wasser und hartem Wasser bei jeweils von 8,4&deg; dH- 14&deg; dH und &uuml;ber 14&deg; dH liegen.</p>
    <p><b>Ammoniumkonzentration</b></p>
    <p>Eine erh&ouml;hte Konzentration von Ammonium deuten auf Verschmutzungen des Gew&auml;ssers hin, zum Beispiel durch Eiwei&szlig;stoffe. Jedoch k&ouml;nnen auch Exkremente oder D&uuml;ngerausschwemmungen ins Wasser gelangen. Ist der pH-Wert im basischen Bereich, wandelt sich Ammonium in Ammoniak um, welches auch als Fischgift bezeichnet wird. Bei einer ausreichenden Menge an Sauerstoff bauen Bakterien Ammonium zum giftigen Nitrit um. Nach der deutschen Trinkwasserverordnung gilt ein Grenzwert von 0,5 mg pro Liter. </p>
    <p><b>Nitrit- und Nitratkonzentration</b></p>
    <p>Nitrate sind Salze und Ester der Salpeters&auml;ure. Sie gelten im See als wichtige Nahrungsgrundlage f&uuml;r Algen. </p>
    <p>Nitrit ist ein krebserregender Stoff, welcher im Stickstoffkreislauf als Zwischenprodukt entsteht und bei niedrigen Sauerstoffkonzentrationen aus Nitrat gebildet wird. In unbelasteten Gew&auml;ssern ist die Konzentration von Nitrit jedoch sehr gering. Besonders giftig wirkt Nitrit auf tierische Organismen. Laut der Trinkwasserverordnung gilt ein Grenzwert von 0,1 mg/l, w&auml;hrend Werte ab 1 mg/l als bedrohlich gelten.</p>
    <p>Nitrat ist ein N&auml;hrstoff f&uuml;r Algen und Wasserpflanzen und bildet somit oft einen limitierenden Faktor f&uuml;r Lebensgemeinschaften. Nitrat entsteht im Boden bei der Humusbildung, beim Abbau stickstoffhaltiger D&uuml;ngemittel und r&uuml;hrt au&szlig;erdem von abgestorbenen Pflanzenteilen, G&uuml;lle und unzureichenden Kl&auml;ranlagen. Bei sehr geringer Konzentration von Ammonium- und Nitritionen l&auml;sst  ein hoher Nitratgehalt auf eine bereits durch Remineralisierung abgebauteVerschmutzung schlie&szlig;en. Die Trinkwasserverordnung schreibt einen Grenzwert von 50 mg/l vor.</p>
    <p><b>Orthophosphationen</b></p>
    <p>Normalerweise ist der Gehalt an Orthophosphationen (PO<sub>4</sub><sup>3-</sup>) sehr gering, so dass eine erh&ouml;hte Konzentration als Hinweis f&uuml;r eine Belastung dienen kann. Hohe Konzentrationen verursachen sehr starkes Algen- und Pflanzenwachstum, wodurch die Zahl der Bakterien steigt und in der Folge sich der Sauerstoffgehalt des Gew&auml;ssers gesenkt wird.  Die Konzentration von 0,03 mg/l gilt als Schwellenwert, um die Eutrophierung eines Gew&auml;ssers abzugrenzen. Bei belasteten Gew&auml;ssern tritt neben Orthophosphationen auch das Diphosphat bzw. Polyphosphat auf. Nach der Trinkwasserverordnung gilt ein Grenzwert von 6,7 mg Orthophosphat pro Liter.</p>
    <p><b>Eisen und Silitcat</b></p>
    <p>Eisen tritt haupts&auml;chlich in Verbindungen auf und ist Bestandteil vieler Enzyme. Eine Belastung des Wassers mit Eisen bewirkt eine Tr&uuml;bung des Wassers sowie eine Geschmacksver&auml;nderung. Des Weiteren ist Eisen sehr wichtig f&uuml;r den Stickstoffkreislauf, weil es in einer Verbindung zum Reduzieren von Nitrit verwandt wird.</p>
    <p>Durch Verwitterungsprozesse gelangt Silicat ins Wasser, welches in den meisten Mineralien vorhanden ist. Es ist ein essentielles Mineral und beeinflusst die Stabilit&auml;t von Schilfhalmen. Obwohl giftige Siliziumverbindungen existieren, tritt in Trinkwasser nur Kiesels&auml;ure auf.</p>
        
</div>